name: Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.your-email-provider.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Repository Update Notification'
          body: 'There has been a push to the main branch of the repository.'
          to: ajitparihar87@gmail.com
          from: ajitparihar87@gmail.com
